### ISSUE TITLE
Add public API for equality tests, numerical evaluation

### ISSUE THREAD

**Issue by zvxryb** [MatthewJA/Coffeequate#111]
This functionality is mostly implemented, but it is not exposed through the abstract Expression interface.  I exposed these methods in my fork, but I wasn't sure if they were intentionally omitted from the public API on upstream.
The two features I am most interested in are
* Testing equality of expressions:  
Available internally with the `.equals` method, but there should be a public interface which converts both operands to canonical form before comparing them.  See 17cad38b4f1a80b13919cd1c0d59e6a3a081ea0b
* Numerical evaluation  
Numerical evaluation exists for terminals/constants (`.evaluate`), but not for expressions.  I have added a `.approx` method which evaluates expressions as well as terminals.  See b59affd78ec1f1b11158d7cb0b2bd3484a5334e3

**Comment by MatthewJA** [comment]
I totally agree about `.equals`! The reason that's not publicly exposed is because I wasn't 100% convinced that `expandAndSimplify` would return the same form for two things that are equal but potentially entered really weirdly. That's probably not actually a problem (I just never comprehensively tested it and subsequently forgot about it), so I'm happy to have that exposed.

Regarding `.approx` - I'm equally happy having that as a method, so if you submit a pull request or something I'll check it out.

**Comment by bshlgrs** [comment]
I still want a "monte Carlo equals" method which substitutes random values to approximately test equality of expressions.

**Comment by MatthewJA** [comment]
I have no objections to this. It should be pretty easy to implement within the existing framework, too.

**Comment by zvxryb** [comment]
Created a pull request for each.

**Comment by MatthewJA** [comment]
Resolved #112 and #113. Again, sorry about the delay!
